### PR TITLE
Handle binary data on stdin

### PR DESCRIPTION
**Pull request by amshinde**

### CODE REVIEW

**Comment by dlespiau** [comment]
The two commits should be merged, every commit should compile.

**Comment by amshinde** [comment]
Done

**Comment by amshinde** [comment]
@dlespiau ^

**Comment by dlespiau** [comment]
I guess we should have a unit test sending data with a 0 in the middle of it and ensure we do receive on the hyperstart end. Filed https://github.com/clearcontainers/shim/issues/23.

lgtm

[Approved with PullApprove](https://pullapprove.com/clearcontainers/shim/pull-request/22/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=clearcontainers/shim) [Approved with PullApprove](https://pullapprove.com/clearcontainers/shim/pull-request/22/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=clearcontainers/shim)

**Pull request merged**
