### PR TITLE
CI: Enable checkcommits

### LINKED ISSUE #40: Enable checkcommits tool
Add support for https://github.com/clearcontainers/tests/tree/master/cmd/checkcommits, to match the runtimes.

### PR DESCRIPTION
**Pull request by jodh-intel**
Run the checkcommits tool for all PRs under TravisCI.

Fixes #40.

Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

### CODE REVIEW

**Comment by chavafg** [comment]
@jodh-intel Hi, 

I have raised #42 to add semaphoreCI checks for this repo, and we can add the `checkcommits` call in the `.ci/setup.sh` and change the file name that is called in the `travis.yml` file. 

What do you think? That way we can remove the `.ci/ci-setup.sh` and reduce the number of scripts there.

**Comment by jodh-intel** [comment]
Hi @chavafg - sounds good to me.

**Comment by jodh-intel** [comment]
I'll rework this PR once #42 has landed.

**Comment by grahamwhaley** [comment]
Just a note for @jodh-intel #42 has now landed :-)

**Comment by jodh-intel** [comment]
@grahamwhaley - thanks, branch updated.

**Comment by grahamwhaley** [comment]
lgtm
but you still have a WIP/DNM label attached - deliberate?

[Approved with PullApprove](https://pullapprove.com/clearcontainers/shim/pull-request/41/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=clearcontainers/shim)

**Comment by jodh-intel** [comment]
@grahamwhaley - removed ;)

**Comment by amshinde** [comment]
lgtm

[Approved with PullApprove](https://pullapprove.com/clearcontainers/shim/pull-request/41/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=clearcontainers/shim) [Approved with PullApprove](https://pullapprove.com/clearcontainers/shim/pull-request/41/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=clearcontainers/shim)

**Pull request merged**
