### PR TITLE
release: Clear Containers releae 3.0.6

### PR DESCRIPTION
**Pull request by jcvenegas**
Version bump for Clear Containers 3.0.6

Fixes: #86

Signed-off-by: Jose Carlos Venegas Munoz <jose.carlos.venegas.munoz@intel.com>

### CODE REVIEW

**Comment by sboeuf** [comment]
LGTM

[Approved with PullApprove](https://pullapprove.com/clearcontainers/shim/pull-request/99/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=clearcontainers/shim)

**Comment by devimc** [comment]
lgtm

[Approved with PullApprove](https://pullapprove.com/clearcontainers/shim/pull-request/99/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=clearcontainers/shim)

**Comment by sameo** [comment]
LGTM

[Approved with PullApprove](https://pullapprove.com/clearcontainers/shim/pull-request/99/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=clearcontainers/shim) [Approved with PullApprove](https://pullapprove.com/clearcontainers/shim/pull-request/99/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=clearcontainers/shim)

**Review by grahamwhaley — APPROVED** [review]
lgtm

**Comment by gorozco1** [comment]
lgtm

[Approved with PullApprove](https://pullapprove.com/clearcontainers/shim/pull-request/99/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=clearcontainers/shim)

**Pull request merged**
