### PR TITLE
CI: Add additional project approver

### LINKED ISSUE #43: Add additional project approver
Add @grahamwhaley as a project approver.

### PR DESCRIPTION
**Pull request by jodh-intel**
Add @grahamwhaley as an additional project approver.

Fixes #43.

Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

### CODE REVIEW

**Comment by jodh-intel** [comment]
Sorry about the additional whitespace change, but I don't know how to configure my editor to be broken to not fix that issue ;)

**Comment by jodh-intel** [comment]
It looks like semaphore is failing as the semaphore config has already been updated for #42, but that PR hasn't landed yet.

**Comment by grahamwhaley** [comment]
blame the editor eh? :-)
that semaphore thing - that is nuts. I presume we suspect some sort of caching. Guess we wait for #42 to land and retry/rebase... I'll go have a peek at that PR.
other than that...

lgtm

[Approved with PullApprove](https://pullapprove.com/clearcontainers/shim/pull-request/44/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=clearcontainers/shim)

**Comment by amshinde** [comment]
lgtm

[Approved with PullApprove](https://pullapprove.com/clearcontainers/shim/pull-request/44/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=clearcontainers/shim) [Approved with PullApprove](https://pullapprove.com/clearcontainers/shim/pull-request/44/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=clearcontainers/shim)

**Comment by chavafg** [comment]
seems like this will need a rebase to make semaphore happy

**Comment by jodh-intel** [comment]
@chavafg - done.

**Comment by grahamwhaley** [comment]
gak - this looks like a crio breakage on semaphore :-(

**Comment by jodh-intel** [comment]
Ref: https://github.com/clearcontainers/tests/pull/128.

**Pull request merged**
