### PR TITLE
Create CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by egernst**
Add code of conduct based on contributor covenant v1.4.

Signed-off-by: Eric Ernst <eric.ernst@intel.com>

### CODE REVIEW

**Comment by amshinde** [comment]
@egernst Can you add a subsystem to the commit message?

**Comment by egernst** [comment]
sure, done

**Review by amshinde — APPROVED** [review]
lgtm

**Comment by egernst** [comment]
we're looking @ creating a mailing list for CoC issues, so this PR will need updating

**Comment by iphutch** [comment]
This reads great but please note line length in the update. Best practice for .md files is 78 characters.

**Comment by egernst** [comment]
hey @iphutch -- I thought this was on another post - my apologies.

ACK your feedback, but this is coming as template from github directly and is from a different project.  Since it is autogenerated, I'd rather not change what was provided.

**Comment by egernst** [comment]
updated with new mail address

**Comment by egernst** [comment]
@iphutch - can you take another look?

**Review by iphutch — APPROVED** [review]
lgtm

**Comment by jodh-intel** [comment]
lgtm

[Approved with PullApprove](https://pullapprove.com/clearcontainers/shim/pull-request/59/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=clearcontainers/shim)

**Comment by jodh-intel** [comment]
@egernst - looks like jenkins is asleep (we've seen this a few times but have no idea what is wrong).

Could you force a rebase and re-push to wake it up?

**Comment by egernst** [comment]
kicked it -- we'll see soon.  Thanks @jodh-intel

**Pull request merged**
