### PR TITLE
Revendor packages, update references used in earlier versions of packages.

### PR DESCRIPTION
**Pull request by amshinde**

### CODE REVIEW

**Comment by jodh-intel** [comment]
Typo in e404ce7feed30b8523005b1478e84e7d42554e16.

Also, please can you add a git shortlog to the commit that updates the vendoring so we can see what changed.

**Comment by amshinde** [comment]
@jodh-intel Fixed the typo. I am afraid the git shortlog is going to too long, I have added details about the version updates for virtcontainers and proxy instead.

**Comment by jodh-intel** [comment]
ok.

lgtm

[Approved with PullApprove](https://pullapprove.com/clearcontainers/shim/pull-request/58/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=clearcontainers/shim)

**Comment by amshinde** [comment]
@mcastelino Can you approve this one ?

**Review by mcastelino — APPROVED** [review]
LGTM

**Pull request merged**
