### PR TITLE
3.0.0-alpha.3 release

### PR DESCRIPTION
**Pull request by dlespiau**
Detect SIGKILL

Shortlog:

a84379d shim: Handle a SIGKILL signal

Signed-off-by: Damien Lespiau <damien.lespiau@intel.com>

### CODE REVIEW

**Comment by grahamwhaley** [comment]
lgtm

[Approved with PullApprove](https://pullapprove.com/clearcontainers/shim/pull-request/45/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=clearcontainers/shim)

**Comment by amshinde** [comment]
lgtm

[Approved with PullApprove](https://pullapprove.com/clearcontainers/shim/pull-request/45/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=clearcontainers/shim) [Approved with PullApprove](https://pullapprove.com/clearcontainers/shim/pull-request/45/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=clearcontainers/shim)

**Comment by chavafg** [comment]
just as #44, this may need rebase to make semaphore build pass

**Comment by grahamwhaley** [comment]
but, this is a release - can we sensibly do a rebase?, or do we have to include #42 in our release to get semaphore to pass (iyswim)

**Comment by chavafg** [comment]
there is no problem by not including #42 on this release as it was a CI change, but not sure if this can be merged with the semaphoreCI failure.

**Comment by dlespiau** [comment]
I'll redo the release and retag, etc...

**Comment by gorozco1** [comment]
why we do not just relase alpha.4 ?

**Comment by dlespiau** [comment]
The semaphore build seems to be stuck, @chavafg are you the one able to re-trigger semaphore builds?

**Comment by chavafg** [comment]
Relaunched the semaphore build, lets see how it goes now, it is strange that it lasted around 1 hr, but I do not find where the time went.

**Pull request merged**
