### PR TITLE
readme: Add Jenkins build badges

### LINKED ISSUE #72: Add Jenkins build badges

### PR DESCRIPTION
**Pull request by sboeuf**
Adds the missing Jenkins build badges.

Fixes #72

### CODE REVIEW

**Comment by sboeuf** [comment]
@amshinde please take a look

**Comment by sboeuf** [comment]
@iphutch please take a look

**Review by iphutch — APPROVED** [review]
lgtm

**Review by amshinde — APPROVED** [review]
lgtm

**Pull request merged**
