### PR TITLE
travis: Fix the build for coverity scan.

### PR DESCRIPTION
**Pull request by amshinde**
Run autogen.sh script before make for the branch used
for coverity scans

Signed-off-by: Archana Shinde <archana.m.shinde@intel.com>

### CODE REVIEW

**Comment by sboeuf** [comment]
LGTM

[Approved with PullApprove](https://pullapprove.com/clearcontainers/shim/pull-request/19/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=clearcontainers/shim)

**Comment by jcvenegas** [comment]
lgtm

[Approved with PullApprove](https://pullapprove.com/clearcontainers/shim/pull-request/19/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=clearcontainers/shim)

**Comment by jodh-intel** [comment]
lgtm

[Approved with PullApprove](https://pullapprove.com/clearcontainers/shim/pull-request/19/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=clearcontainers/shim)

**Comment by jodh-intel** [comment]
Hi @dlespiau - could you review this? Only you have "the power"! :smile:

**Comment by dlespiau** [comment]
lgtm

[Approved with PullApprove](https://pullapprove.com/clearcontainers/shim/pull-request/19/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=clearcontainers/shim) [Approved with PullApprove](https://pullapprove.com/clearcontainers/shim/pull-request/19/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=clearcontainers/shim)

**Pull request merged**
