### PR TITLE
# Clear Containers 3.0.17

### PR DESCRIPTION
**Pull request by erick0z**
## Changes
No Changes

### CODE REVIEW

**Comment by jodh-intel** [comment]
I'm assuming no changes this time round. Could you just add "No changes" or something to make it clear though? Once done,

lgtm

[Approved with PullApprove](https://pullapprove.com/clearcontainers/shim/pull-request/125/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=clearcontainers/shim)

**Comment by jcvenegas** [comment]
Failed trying to build cri-o @egernst  @chavafg is there any open issue related with this?
```bash
00:04:58.453 Get CRI-O sources
00:05:03.805 package github.com/kubernetes-incubator/cri-o: no Go files in /home/jenkins/jenkins_slave/workspace/clear-containers-shim-azure-ubuntu-17-10-PR/go/src/github.com/kubernetes-incubator/cri-o
00:05:03.805 ~/jenkins_slave/workspace/clear-containers-shim-azure-ubuntu-17-10-PR/go/src/github.com/kubernetes-incubator/cri-o ~/jenkins_slave/workspace/clear-containers-shim-azure-ubuntu-17-10-PR/go/src/github.com/clearcontainers/tests
00:05:04.307 Note: checking out 'v1.0.4'.
00:05:04.307 
00:05:04.307 You are in 'detached HEAD' state. You can look around, make experimental
00:05:04.307 changes and commit them, and you can discard any commits you make in this
00:05:04.307 state without impacting any branches by performing another checkout.
00:05:04.307 
00:05:04.307 If you want to create a new branch to retain commits you create, you may
00:05:04.307 do so (now or later) by using -b with the checkout command again. Example:
00:05:04.308 
00:05:04.308   git checkout -b <new-branch-name>
00:05:04.308 
00:05:04.309 HEAD is now at 4aceedee... version: bump to v1.0.4
00:05:04.311 ln: target '/home/jenkins/jenkins_slave/workspace/clear-containers-shim-azure-ubuntu-17-10-PR/go/bin/' is not a directory: No such file or directory
00:05:04.325 Build step 'Execute shell' marked build as failure
00:05:04.406 Performing Post build task...
00:05:04.406 Could not match :Build was aborted  : False
00:05:04.406 Match found for :Build step 'Execute shell' marked build as failure : True
00:05:04.406 Logical operation result is TRUE
00:05:04.406 Running script  : #!/bin/bash
00:05:04.406 
00:05:04.406 export GOPATH=$WORKSPACE/go
00:05:04.406 
00:05:04.406 cd $GOPATH/src/github.com/clearcontainers/tests
00:05:04.406 .ci/teardown.sh "$WORKSPACE"
00:05:04.411 [clear-containers-shim-azure-ubuntu-17-10-PR] $ /bin/bash /tmp/jenkins1291353103035605201.sh
00:05:04.429 ~/jenkins_slave/workspace/clear-containers-shim-azure-ubuntu-17-10-PR ~/jenkins_slave/workspace/clear-containers-shim-azure-ubuntu-17-10-PR/go/src/github.com/clearcontainers/tests
00:05:04.458 ~/jenkins_slave/workspace/clear-containers-shim-azure-ubuntu-17-10-PR/go/src/github.com/clearcontainers/tests
00:05:04.471 POST BUILD TASK : SUCCESS
00:05:04.471 END OF POST BUILD TASK : 0
00:05:04.471 Archiving artifacts
00:05:05.818 Setting status of ec302f750687914c143dcf76062e251f6845327a to FAILURE with url http://cc-jenkins-ci.westus2.cloudapp.azure.com/job/clear-containers-shim-azure-ubuntu-17-10-PR/44/ and message: 'Build finished. '
00:05:05.818 Using context: jenkins-ci-ubuntu-17-10
00:05:05.992 Finished: FAILURE
```

**Comment by chavafg** [comment]
@jcvenegas https://github.com/clearcontainers/tests/pull/903 fixes the issue

**Comment by sameo** [comment]
LGTM

[Approved with PullApprove](https://pullapprove.com/clearcontainers/shim/pull-request/125/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=clearcontainers/shim) [Approved with PullApprove](https://pullapprove.com/clearcontainers/shim/pull-request/125/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=clearcontainers/shim)

**Pull request merged**
