### PR TITLE
Add missing vargs call

### PR DESCRIPTION
**Pull request by jodh-intel**

### CODE REVIEW

**Review by grahamwhaley — APPROVED** [review]
lgtm
@jodh-intel I presume you did intend to submit the three patches (checking, as the PR only referes to the va_end one iyswim)

**Comment by jodh-intel** [comment]
... cough...

**Comment by grahamwhaley** [comment]
I believe there is nothing stopping this being merged once it has another review - is there @jodh-intel (I think you got rid of your cough right? ;-) )

**Comment by jodh-intel** [comment]
Hi @amshinde - could you take a look?

**Review by amshinde — APPROVED** [review]
lgtm

**Pull request merged**
